<a href="https://colab.research.google.com/github/honey-python-world/Numpy/blob/main/iterate_Numpy_Array_Using_nditer.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np 

In [2]:
a= np.arange(12).reshape(3,4)

In [3]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [4]:
for row in a:
  for cell in row:
    print(cell)

0
1
2
3
4
5
6
7
8
9
10
11


In [6]:
for cell in a.flatten():
  print(cell)

0
1
2
3
4
5
6
7
8
9
10
11


In [5]:
for i in a:
  print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


## Numpy function nditer() function

In [11]:
for i in np.nditer(a,order="C"):
  print(i)# order ="c" means in  access the arrays  like in  c langauge
  # order ="f" means in  access the arrays  like in  Fortran langauge
  

0
1
2
3
4
5
6
7
8
9
10
11


# op_flag on for loop

In [13]:
for x in np.nditer(a,order="f", flags=["external_loop"]):
  print(x)

[0 4 8]
[1 5 9]
[ 2  6 10]
[ 3  7 11]


In [14]:
for x in np.nditer(a,op_flags=["readwrite"]):
  x[...]=x*x

In [15]:
a

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [16]:
# when i want to iterate the two arrays  

In [18]:
b=np.arange(3,15,4).reshape(3,1)
b

array([[ 3],
       [ 7],
       [11]])

In [19]:
for x,y in np.nditer([a,b]):
  print(x,y)

0 3
1 3
4 3
9 3
16 7
25 7
36 7
49 7
64 11
81 11
100 11
121 11
