<a href="https://colab.research.google.com/github/honey-python-world/Numpy/blob/main/Numpy_Tutorials.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np 


In [14]:
a=np.array([1,2,3])

In [5]:
a

array([1, 2, 3])

In [7]:
a[0]

1

In [6]:
a[1]

2

In [19]:
b=np.array([[1,2],[3,4],[5,6]])

In [12]:
b.ndim

2

In [15]:
a.ndim

1

In [16]:
b.itemsize

8

In [17]:
a.dtype

dtype('int64')

In [20]:
b.dtype

dtype('int64')

In [21]:
b=np.array([[1,2],[3,4],[5,6]], dtype=np.float64)

In [22]:
b.itemsize

8

In [23]:
b

array([[1., 2.],
       [3., 4.],
       [5., 6.]])

In [24]:
a.size

3

In [25]:
b.size

6

In [26]:
a.shape

(3,)

In [27]:
b.shape

(3, 2)

In [28]:
c=np.array([[1,2],[3,4],[5,6]], dtype=complex)

In [29]:
c

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j],
       [5.+0.j, 6.+0.j]])

In [30]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [31]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

# Range functions

In [33]:
list= range(0,5)

In [34]:
list[1]

1

In [35]:
list[0]

0

In [36]:
list[2]

2

In [40]:
np.arange(1,10)

array([1, 2, 3, 4])

In [41]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

Linspace Function

In [42]:
np.linspace(1,5,10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [43]:
np.linspace(1,5,5)

array([1., 2., 3., 4., 5.])

In [44]:
np.linspace(1,5,20)

array([1.        , 1.21052632, 1.42105263, 1.63157895, 1.84210526,
       2.05263158, 2.26315789, 2.47368421, 2.68421053, 2.89473684,
       3.10526316, 3.31578947, 3.52631579, 3.73684211, 3.94736842,
       4.15789474, 4.36842105, 4.57894737, 4.78947368, 5.        ])

## reshape Function

In [48]:
b=np.array([[1,2],[3,4],[5,6]])

In [49]:
b

array([[1, 2],
       [3, 4],
       [5, 6]])

In [46]:
b.shape

(3, 2)

In [51]:
b.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [55]:
b.reshape(6,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [56]:
b.ravel()

array([1, 2, 3, 4, 5, 6])

In [57]:
b

array([[1, 2],
       [3, 4],
       [5, 6]])

In [59]:
b.min()

1

In [60]:
b.max()

6

In [61]:
b.sum()

21

In [63]:
b.sum(axis=0)

array([ 9, 12])

In [64]:
b.sum(axis=1)

array([ 3,  7, 11])

In [65]:
 np.sqrt(b)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ],
       [2.23606798, 2.44948974]])

In [66]:
b

array([[1, 2],
       [3, 4],
       [5, 6]])

## Standard devation function std()

In [67]:
np.std(b)

1.707825127659933

In [68]:
np.std(a)

0.816496580927726

Simple arithematic function

In [74]:
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])

In [75]:
a


array([[1, 2],
       [3, 4]])

In [76]:
b

array([[5, 6],
       [7, 8]])

In [77]:
a+b

array([[ 6,  8],
       [10, 12]])

In [78]:
a*b

array([[ 5, 12],
       [21, 32]])

In [79]:
a/b

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

In [80]:
a.dot(b)

array([[19, 22],
       [43, 50]])

In [81]:
b.dot(a)

array([[23, 34],
       [31, 46]])