<a href="https://colab.research.google.com/github/honey-python-world/Numpy/blob/main/Slicing_Stacking_Arrays_%2CIndexing_with_Boolean_Arrays.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np 


In [19]:
n=[6,7,8]

In [20]:
n[0:2]

[6, 7]

In [21]:
n[-1]

8

In [22]:
a=np.array([6,7,8])

In [23]:
a[0:2]

array([6, 7])

In [25]:
a[-1]# last element in the array

8

In [26]:
a=np.array([[6,7,8],[1,2,3],[9,3,2]])

In [27]:
a


array([[6, 7, 8],
       [1, 2, 3],
       [9, 3, 2]])

In [29]:
a[1,2]# 1st row and second column

3

In [30]:
a[0:2,2]

array([8, 3])

In [32]:
a[-1] # last row in the array

array([9, 3, 2])

In [33]:
a[-1,0:2]

array([9, 3])

In [34]:
a[:,1:2]

array([[7],
       [2],
       [3]])

In [37]:
a[:,1:3]

array([[7, 8],
       [2, 3],
       [3, 2]])

# iterate through array

In [38]:
a

array([[6, 7, 8],
       [1, 2, 3],
       [9, 3, 2]])

In [39]:
for row in a:
  print(row)

[6 7 8]
[1 2 3]
[9 3 2]


In [45]:
for cell in a.flat:
  print(cell," ")
  #print()

6  
7  
8  
1  
2  
3  
9  
3  
2  


## Sticking together two array

In [46]:
a=np.arange(6)

In [47]:
a

array([0, 1, 2, 3, 4, 5])

In [49]:
a=np.arange(6).reshape(3,2)

In [51]:
a# box1

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [53]:
b=np.arange(6,12).reshape(3,2)

In [54]:
b#Box2

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [55]:
a+b

array([[12, 14],
       [16, 18],
       [20, 22]])

In [58]:
np.vstack((a,b))# Making two  boxes in  one Big


array([[ 6,  7],
       [ 8,  9],
       [10, 11],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [60]:
np.vstack((a,b)).reshape(4,3)

array([[ 6,  7,  8],
       [ 9, 10, 11],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [61]:
np.hstack((a,b))

array([[ 6,  7,  6,  7],
       [ 8,  9,  8,  9],
       [10, 11, 10, 11]])

In [65]:
a=np.arange(30).reshape(2,15)

In [66]:
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [ ]:
#split the array into two 

In [64]:
np.hsplit(a,3)

[array([[ 0,  1,  2,  3,  4],
        [15, 16, 17, 18, 19]]), array([[ 5,  6,  7,  8,  9],
        [20, 21, 22, 23, 24]]), array([[10, 11, 12, 13, 14],
        [25, 26, 27, 28, 29]])]

In [67]:
result=np.hsplit(a,3)

In [68]:
result[0]

array([[ 0,  1,  2,  3,  4],
       [15, 16, 17, 18, 19]])

In [69]:
result[1]

array([[ 5,  6,  7,  8,  9],
       [20, 21, 22, 23, 24]])

In [70]:
result[2]

array([[10, 11, 12, 13, 14],
       [25, 26, 27, 28, 29]])

In [71]:
result=np.vsplit(a,2)

In [72]:
result[0]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14]])

In [73]:
result[1]

array([[15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

Indexing with boolean array

In [81]:
a=np.arange(0,12).reshape(3,4)

In [83]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [84]:
b=a>4

In [85]:
b

array([[False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True]])

In [86]:
a[b]

array([ 5,  6,  7,  8,  9, 10, 11])

In [87]:
#Replacing with some other number
a[b]= -1

In [88]:
a

array([[ 0,  1,  2,  3],
       [ 4, -1, -1, -1],
       [-1, -1, -1, -1]])